- class-wc-gateway-komoju.php
- includes/class-wc-gateway-komoju-request.php
- includes/class-wc-gateway-komoju-response.php
When hitting the "Back" button in your browser and selecting a new payment
method Komoju will complain that the order ID is no longer unique preventing you
from creating a payment.
This pull request tacks on a random 6 letter string every time a payment request is made.
When the callback is processed the prefix and the suffix are stripped to get the order number.
Tested capturing the payment which works:
> Add unique order prefix for each payment request

- MIT-LICENSE
- README.md
Unfortunately maintaining a WooCommerce plugin is not a priority, so I'm adding this message and license to warn users that we cannot provide support for issues encountered using it right now. We may change this stance in the future, but for now I think it's better to be transparent.
> Add license and message to readme

- class-wc-gateway-komoju.php
After submitting the plugin to WordPress.org we were informed that we needed to implement sanitisation on the payment method field, before using it to construct the hosted page URL.
> Sanitise user input for payment method

- includes/class-wc-gateway-komoju-request.php
Coupon discounts are not being correctly applied. When a coupon discount is added to the order, it correctly discounts the cost on the WooCommerce site, but once the user is directed to the Hosted Payments page, the full undiscounted price is being displayed (and charged):
WooCommerce checkout screen
KOMOJU Hosted Page checkout screen (for konbini)
When calculating the order amount we combine together several different order price fields (order subtotal & total shipping cost). The problem with this is that the order subtotal is the base price of the item without additional tax or discount amounts applied. So when we create the payment we aren't applying the discount.
The [`order->getTotal()`](https://woocommerce.github.io/code-reference/classes/WC-Abstract-Order.html#method_get_total) …
> Fix: include discounts in amount being charged

- class-wc-gateway-komoju.php
- includes/class-wc-gateway-komoju-ipn-handler.php
- includes/class-wc-gateway-komoju-response.php
- komoju-php/komoju-php/lib/komoju/KomojuApi.php
Uses the Sessions API in place of the legacy hosted page.
This PR removes the old request class but retains the logic surrounding the IPN (webhooks)
Note that redirect after checkout will not work properly until the fix for multiple query parameters is deployed. This PR should not be merged until then
1. `docker-compose up`
2. follow the development setup instructions on this repository
3. add a product to cart and navigate to checkout page 
4. complete the checkout flow
> Migrate to Sessions API

- .gitattributes
- .github/workflows/deploy.yml
Uploading changes manually to the wordpress svn is error prone. Adding an action to automate it
Using a third party action that can be reviewed here: https://github.com/10up/action-wordpress-plugin-deploy
> Deploy action

- class-wc-gateway-komoju.php
Add a Filter to $komoju_client->paymentMethods()
`$methods = apply_filters( 'woocommerce_komoju_payment_methods', $komoju_client->paymentMethods());`
So that we can remove unwanted payment methods from Woocommerce checkout page
> Add a Filter to $komoju_client->paymentMethods()

- Dockerfile
- class-wc-gateway-komoju.php
- index.php
- readme.txt
Bumping version to 2.1.0, to deploy changes in #42.
We've automated the deploy based on pushing tags, so once this PR is approved I'll tag the commit on master as `v2.1.0` and deploy it to WordPress.
> Bump version

- class-wc-gateway-komoju.php
This is a quick amendment to our /api/v1/sessions call to make it send [line items](https://docs.komoju.com/en/hosted_page/cheatsheet/#with_full_line_items). Line items let us see product info directly on the payment screen.
https://user-images.githubusercontent.com/2793160/152509946-ab69d821-02f2-4abd-b461-25b2e66d714a.mp4
> Send line item info to KOMOJU

- class-wc-gateway-komoju.php
I noticed clicking on the payment method text does not select the radio input associated with it.
This pull request wraps each input element in a <label> tag so when clicking on the text it will select the radio button input.
Also for some strange reason "Method of payment:" was wrapped in a <label> input tag. I've remove it in this pull request.
> Fix radio button selection input

- class-wc-gateway-komoju.php
- index.php
- readme.txt
On the [Wordpress store](https://ja.wordpress.org/plugins/komoju-japanese-payments/) we refer to the plugin as "KOMOJU Japanese Payments". However, we now support a variety of payment methods all around the world, so we should update the plugin details to reflect that.
1. Run the app locally with `docker-compose up`
2. go to `http://localhost:8000`
3. Set up your admin account (with whatever details you want)
4. on the dashboard, go the "Plugins" on the side, and confirm you can see "KOMOJU Payments" as the plugin name
> Update plugin name to be KOMOJU Payments

- .github/workflows/test.yml
- .gitignore
- Dockerfile
- class-wc-settings-page-komoju.php
- docker-compose.yml
- tests/README.md
- tests/cypress.json
- tests/cypress/integration/admin.spec.js
- tests/cypress/integration/checkout.spec.js
- tests/cypress/integration/plugin.spec.js
- tests/cypress/plugins/index.js
- tests/cypress/support/commands.js
- tests/cypress/support/index.js
- tests/package-lock.json
- tests/package.json
Heads up! **The huge line count is 99% package-lock.json**. The actual content of this PR is much smaller.
This PR introduces some integration tests we can use to validate the behavior of this plugin as it grows larger.
The testing framework is [https://cypress.io](Cypress), which provides a very nice interface for inspecting running specs and troubleshooting.
One downside of all this is that there is a lot of boilerplate setup that goes against the Cypress best practices of keeping tests self-contained. Basically, the first time the tests are run, we need to install wordpress and install woocommerce. The install process is lengthy and error-prone. Unfortunately, I don't know of a better way to automate those tasks right now.
0. `docker-compose down --volumes; docker-compose up`
1. `cd …
> Add automated tests with Cypress

- class-wc-gateway-komoju.php
We support multi-currency now, so this code is now more harmful than helpful.
> Remove currency check

- .github/workflows/test.yml
- build.bash
- class-wc-gateway-komoju.php
- includes/class-wc-gateway-komoju-ipn-handler.php
- includes/class-wc-gateway-komoju-single-slug.php
- komoju-php/komoju-php/lib/komoju/KomojuApi.php
Right now we only sync refunds from KOMOJU. For better plugin interoperability and UX, we'd like to also support refunding from WC.
This PR also adds a CI step that actually tests the feature via our E2E tests.
1. Basic setup: `docker-compose up` and visit http://localhost:8000/wp-admin (install WC and komoju plugins if necessary)
1. You'll need to use ngrok or similar in order to receive webhooks
2. Visit your store via ngrok
3. Go to WooCommerce settings, click the KOMOJU tab, then sign into komoju
4. Enable credit card or some other refundable payment method like paypay
5. Visit your store and buy a product using credit card or paypay
6. Find the order on your WooCommerce admin
7. You should be able to refund it via KOMOJU
8. Check KOMOJU to make sure it's actually refunded
> Support refunding from WooCommerce

- class-wc-gateway-komoju.php
- includes/class-wc-gateway-komoju-ipn-handler.php
- includes/class-wc-gateway-komoju-response.php
- tests/cypress/integration/checkout.spec.js
There are some stores that expire the checkout as soon as the user begins payment. Right now, this plugin returns the user to checkout when they click "return to merchant" on KOMOJU. For stores that expire the checkout, this behavior shows an error when the user tries to return to the store.
This PR changes the plugin behavior. Instead of returning to checkout, we now return to the pay-order page for the existing order (this is pretty subtle, honestly. there's barely any difference on the default development store).
https://user-images.githubusercontent.com/2793160/175858707-108d2dc0-6b34-4da9-a441-3fd5bcca615d.mp4
1. Start a payment through WooCommerce
2. Click "back to merchant" from the KOMOJU session page
3. You should be back on the store, but not the checkout. Your url should …
> Return to pay-order URL instead of checkout

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- index.php
- readme.txt
Locale strings often look like `en_US` or `ko_KR`. Before this PR, the plugin would not properly treat `ko_KR` as `ko`.
> Fix locales with country code

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- includes/class-wc-gateway-komoju-ipn-handler.php
- index.php
- readme.txt
We were assuming that the admin is always located at /wp-admin/admin.php. This PR fixes that, allowing the quick setup feature to work regardless of where admin.php is located.
> Make quick setup work on shops with a scoped root path

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- index.php
- readme.txt
We're having trouble where another plugin is unable to refund due to missing komoju gateways. I haven't been able to reproduce this myself, but I suspect it might be because of an odd if-statement we had in our index.php. This PR removes that if-statement.
> Make plugin always add gateway filter

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- includes/class-wc-gateway-komoju-ipn-handler.php
- includes/class-wc-gateway-komoju-webhook-event.php
- index.php
- readme.txt
We need to validate the order amount on capture to make sure the order contents didn't change before payment was completed.
This is a little tricker when dynamic currency conversion is being used, since the payment amount will almost certainly not be the same as the order amount. In such cases, we can check against the session amount instead of the payment amount.
> Fix amount validation in dynamic currency scenarios

- includes/class-wc-gateway-komoju-ipn-handler.php
Fixes (https://github.com/degica/komoju-woocommerce/issues/83)
Fixed this issue.
> A merchant asked us about some orders and told us cancellation webhook event was received for the Woocommerce order after a successful capture. It turns out such orders have multiple payments. So a problem happens when a payment is captured for an order but another payment for the same order gets cancelled, which cancels the order when it shouldn't.
Fixed to abort cancellation process if order's transaction_id does not match with webhookEvent.
(The transaction_id of order is set when the payment is captured.)
https://github.com/degica/komoju-woocommerce/blob/master/includes/class-wc-gateway-komoju-ipn-handler.php#L208
There are many steps to the test, so we have included a video. Please refer to it.
1. I'd …
> Fix for multiple payments.

- class-wc-gateway-komoju.php
The link currently points to the new admin pages we're building, but while the new dashboard is in beta we should redirect all users to the existing, stable implementation by default.
> Redirect merchant to old (stable) URL for payments link

- tests/cypress/e2e/checkout.cy.js
- tests/cypress/support/commands.js
I updated test codes to pass the tests with the latest environment. The following changes were covered by this PR changes.
- Some labels are uppercased with CSS. Cypress requires `matchCase` option to be specified to ignore cases today.
- WooCommerce changed the billing form:
- It uses combo boxes for country and state and it has the hidden select forms.
- It validates a postal code.
Please confirm the CI passed.
> Fix failing tests

- docker-compose.yml
- includes/class-wc-gateway-komoju-ipn-handler.php
- tests/cypress/e2e/refunded-webhook.cy.js
- tests/cypress/support/commands.js
Fixing refund webhook issue for decimal currency orders (e.g., HKD). The plugin now properly converts amounts to cents for accurate comparisons.
> Fix occasionally not handling refund webhooks

- readme.txt
Fixes: https://app.asana.com/0/1204577477850530/1206355454744621/f (see item 2 of pinned comment)
This PR updates the plugin documentation that appears on https://ja.wordpress.org/plugins/komoju-japanese-payments/: 
1. Update compatability versions that will appear on the details tab
2. Add an item to the FAQ section for merchants already on newer versions
> Tweak WordPress and WooCommerce compatability versions

- index.php
- readme.txt
Follows: https://github.com/degica/komoju-woocommerce/pull/99
This PR bumps the plugin version to 3.0.6 following the documentation updates from the PR above.
> Bump to 3.0.6

- README.md
- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- index.php
- readme.txt
Fixes top comment from https://app.asana.com/0/1204577477850530/1206355454744621/1206482198931670.
This PR makes the following changes:
* Adds JA translations for the FAQ section
* Attempts to move promote visibility of FAQ section as requested by CS
CS team provided some JA translations for the FAQ section of our plugin's WordPress store page. I poked around our deploy Github action and noticed we are using a third party service to update plugin's store page contents. I'm not entirely clear on how the content is rendered, but I added some documentation to the README to help future developers out 🙌
> Add JA FAQ translation

- tests/cypress/e2e/admin.cy.js
This PR fixes failing E2E: https://github.com/degica/komoju-woocommerce/commit/ac3e69bf64089a07c1b3d92f2481e99e70184909/checks/21135979902/logs
https://requestbin.labs.degica.com is currently down for the count, and after [some discussion](https://degica.slack.com/archives/C03S3UEEE/p1706849843260729) it seems ok to stop using it. In the failing spec the page wasn't loading so cypress hinted the spec exceeding the default `pageLoadTimeout`, so this PR uses a more reliable 🤔 page to attempt and fail a KOMOJU account connection. I think it's safe to send the connection request to example.com?
> Fix E2E admin spec

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- includes/class-wc-gateway-komoju-ipn-handler.php
- index.php
- readme.txt
We got a bug report about webhooks getting dropped after automatic updates. I noticed that we're not following [the official advice on hooks within gateway initializers](https://developer.woo.com/docs/woocommerce-payment-gateway-api/#4-hooks-in-gateways), which might be the cause. This PR moves the API action registration outside of the gateway initialization code. Hopefully this fixes the issue.
I had a hard time reproducing the original issue, but I was able to confirm that this change doesn't break regular webhook processing.
> Try fixing IPN flakiness

- includes/class-wc-gateway-komoju-ipn-handler.php
A merchant discovered the error log during WC maintenance.
```
CRITICAL Uncaught Error: Call to a member function uuid() on null in /home/kusanagi/de300fb99ec8ad9cd9b44e25/DocumentRoot/wp-content/plugins/komoju-japanese-payments/includes/class-wc-gateway-komoju-ipn-handler.php:256
```
The specific line of code causing issues was `$transaction_id == $webhookEvent->uuid()` since `$webhookEvent` wasn't passed to the `is_order_cancellable` function. This PR updates the `is_order_cancellable` method to properly receive `$webhookEvent` so we don't call `uuid` on a nil variable.
Fixes: https://app.asana.com/0/1203431131393579/1206550902062204/f
Probably ok to just check the code on this one. If you want to test it, you can:
1. Setup a local env to test the Komoju WooCommerce plugin (see …
> Fix cancellation webhook bug

- Dockerfile
- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- docker-compose.yml
- frontend.js
- includes/class-wc-gateway-komoju-block.php
- includes/class-wc-gateway-komoju-single-slug.php
- includes/gateway-settings-komoju.php
- includes/js/komoju-checkout-blocks.js
- index.php
- komoju-php/komoju-php/lib/komoju/KomojuApi.php
This pull request updates the KOMOJU WooCommerce integration to be compatible with WooCommerce version 8.8.2. Key updates include modifications to Docker configurations, plugin file adjustments, and enhancements to the checkout block to ensure smooth integration with the latest WooCommerce changes.
- Updated to use WooCommerce version 8.8.2 
- Incremented version numbers in class-wc-gateway-komoju.php and class-wc-settings-page-komoju.php
- New Implementation Files: 
- Added class-wc-gateway-komoju-block.php and associated JavaScript file komoju-checkout-blocks.js to support WooCommerce Blocks. This change allows the KOMOJU payment methods to integrate seamlessly with the new WooCommerce Blocks checkout process.
- index.php: Updated plugin metadata and added registration hooks for the new …
> Update KOMOJU WooCommerce Integration for WooCommerce 8.8.2 Compatibility

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- includes/js/komoju-checkout-blocks.js
- index.php
- readme.txt
After updating 3.1.0, there was huge plugin conflicts.
- Call the gateway in the correct timing
- Add wrapper for javascript for safety
This problem was caused by calling gateway in the wrong timing. Komoju-WooCommerece was working fine, but if other plugins which calling `payment_gateways` it was causing a conflict.
Calling `WC()->payment_gateways->payment_gateways();` in `woocommerce_blocks_loaded`
```php
function register_komoju_payment_method_type()
{
if (!class_exists('Automattic\WooCommerce\Blocks\Payments\Integrations\AbstractPaymentMethodType')) {
return;
}
$gateways = WC()->payment_gateways->payment_gateways();
if ($gateways) {
...
```
Calling `WC()->payment_gateways->payment_gateways();` in `woocommerce_blocks_payment_method_type_registration`
```php …
```
> Fix plugin conflicts in 3.1.0

- includes/class-wc-gateway-komoju-block.php
- includes/class-wc-gateway-komoju-single-slug.php
- includes/js/komoju-checkout-blocks.js
- tests/cypress/e2e/admin.cy.js
- tests/cypress/e2e/checkout.cy.js
- tests/cypress/support/commands.js
This PR introduces logics to avoid rendering hosted fields under circumstances that it shouldn't be rendered.
With 3.1.0, we introduced these 2 changes:
* Support of checkout blocks
* "Truthy" default descriptions of payment methods
As a result an unexpected behaviour was introduced, with which it attempts to render hosted fields unconditionally, even though inline fields are disabled or the publishable key is unset.
It's also worth to mention that there's [a non-intuitive design in the WC side for checkout shortcodes](https://github.com/woocommerce/woocommerce/blob/5dd7713346786c5874615b34a1d56f81a29b673f/plugins/woocommerce/templates/checkout/payment-method.php#L28). Blocks just need an extra logic to control the behaviour.
This PR makes these two specific changes:
* For shortcodes: …
> Prevent rendering fields if should not; use hosted pages instead

- includes/class-wc-gateway-komoju-block.php
- includes/class-wc-gateway-komoju-ipn-handler.php
- includes/class-wc-gateway-komoju-single-slug.php
- index.php
- tests/cypress/e2e/admin.cy.js
- tests/cypress/e2e/checkout.cy.js
- tests/cypress/e2e/refunded-webhook.cy.js
- tests/cypress/support/commands.js
- tests/cypress/support/e2e.js
- tests/package-lock.json
- tests/package.json
This PR updates the KOMOJU Payments plugin to ensure compatibility with WooCommerce's Ceckout block & High-Performance Order Storage ([HPOS](https://woocommerce.com/document/high-performance-order-storage/)) feature. The following changes have been made:
- Added code to declare compatibility with WooCommerce's 'cart_checkout_blocks' and 'custom_order_tables' features.
- Added a check to ensure the plugin does not operate on the 'order-received' endpoint to avoid unnecessary session creation.
- Replaced update_post_meta calls with WC_Order's update_meta_data and save methods to ensure compatibility with HPOS.
- Updated the save_komoju_meta_data function to use update_meta_data instead of update_post_meta.
- There was timing issue in cypress that it was testing without signed in correctly. …
> Update KOMOJU Plugin for WooCommerce Cart Checkout Block & HPOS

- class-wc-settings-page-komoju.php
- tests/cypress/support/commands.js
By default KOMOJU merchants have multicurrency enabled, with which there can by multiple payment methods with the same `type_slug`, but with different `currency` or sets of `subtypes` (card brands).
This PR makes sure that the plugin disposes only payment methods that don't support the currency configured for the WooCommerce instance.
> Examine currency before recognizing as an available payment method

- includes/class-wc-gateway-komoju-ipn-handler.php
- includes/class-wc-gateway-komoju-single-slug.php
- komoju-php/komoju-php/lib/komoju/KomojuApi.php
Konbini payments are unique: There's a considerable time gap between the timing that a payment is ready for capture (payment codes issued, or "authorized" in KOMOJU) and the timing of actual capture. For this purpose, the KOMOJU Payment plugin puts a WooCommerce order pending or on hold when a Konbini payment is "authorized".
During the period that orders on WooCommerce are pending or on-hold, however, WooCommerce allows shoppers to make another payment for the same order, through the page called order-pay (`/checkout/order-pay` - cf https://github.com/woocommerce/woocommerce/blob/4318dac7ecd6547a983148273fd2e278cbb18547/docs/getting-started/woocommerce-endpoints.md#L18). Due to this nature, there are multiple problematic scenarios that can happen, including:
* duplicated payments, …
> Cancel on expiry and duplication of payments

- .github/workflows/test.yml
Our CI/CD process started to fail as there was a breaking change in the underlying test containers: https://github.com/actions/runner-images/issues/9692
This change counters against it.
> Replace direct calls of docker-compose

- Dockerfile
- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- docker-compose.yml
- index.php
- readme.txt
- tests/cypress/e2e/admin.cy.js
- tests/cypress/e2e/checkout.cy.js
- tests/cypress/support/commands.js
- tests/package-lock.json
- tests/package.json
Check compatibility with WooCommerce 9.4.1 and Wordpress 6.7.0 and update the documents
- Updated Docker file to be compatible with new version
- Updated Documents
- Tested payments with the new version
We need to be careful before the release because when we publish the new release, the current users will get notice to update the latest version.
Despite this doesn't have any conflicts with the current WooCommerce we might encounter user reporting conflicts with the other plugins. That is very hard to catch, but we need to aware of it.
> Check compatibility for WooCommerce 9.4.1 and Wordpress 6.7.0

- includes/class-wc-gateway-komoju-block.php
- includes/class-wc-gateway-komoju-single-slug.php
- index.php
- uninstall.php
After having discussion, decided not to create checkout session when cart is null.
> Skip creating checkout session when the cart is empty

- .github/workflows/test.yml
- Dockerfile
- docker-compose.yml
- index.php
- readme.txt
Update WordPress version from 6.7.0 to 6.7.1.
Update WooCommerce from 9.4.1 to 9.5.2
- We must test before the release
> Update both Wordpress and Woocommerce version

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- index.php
The version numbers in the PHP files were still set to 3.1.5, which is outdated. This PR updates the version numbers to 3.1.6 in preparation for the upcoming release.
These changes ensure the version numbers are consistent across all files, aligning with the upcoming release of version 3.1.6.
> Update versions in php to 3.1.6

- .github/workflows/deploy.yml
It appears that svn has been removed from the default Ubuntu image. Adding explicit installation of svn to resolve the deploy issue.
> Fix missing svn install in deploy

- .github/workflows/test.yml
This pull request updates the CI workflow to replace the usage of the `komoju-e2e-test` repository with `valis`. Since `komoju-e2e-test` is deprecated, this change will improve maintainability and compatibility.
1. **Updated Test Workflow**:
- The e2e testing job now uses the `valis` repository instead of `komoju-e2e-test`.
- Added Playwright reporting for improved debugging and test result visibility.
- `TEST_URL` and `DD_API_KEY` have been added in the Github Secrets.
- Simplifies the CI configuration by using a standardized repository (`valis`).
- Leverages modern testing tools (Playwright) for improved e2e testing performance and reliability.
- We need to write more tests in Valis to ensure everything work as expected
> Replace komoju-e2e-test with valis in CI configuration

- class-wc-gateway-komoju.php
- includes/api-settings-komoju.php
- includes/gateway-settings-komoju.php
Fixes #67
Move the option to use the on-hold status for WooCommerce orders under API settings.
Historically this option was available only for `komoju` gateway (the unified one, not for each single payment methods). This is not convenient for most merchants, because they usually don't use the gateway (actually we discourage merchants to use the gateway, in favour of per-payment-method gateways). This PR alleviates the pain by moving the option to a more obvious place, which we determined is the API settings page.
> Move the option to use the on-hold status under API settings

- tests/cypress/e2e/checkout.cy.js
- tests/cypress/e2e/refunded-webhook.cy.js
- tests/cypress/support/commands.js
Cypress test was failing when `USD` currency is selected but trying to pay with `Japanese Konbini` payment method.
- Force set JPY for currency in Setup.
> Fix wrong currency in test

- .github/workflows/docs.yml
- mkdocs.yml
This pull request introduces a GitHub Actions workflow that automatically builds and deploys the KOMOJU WooCommerce plugin documentation using MkDocs.
- **Added `.github/workflows/docs.yml`:** A new workflow file that triggers on documentation-related changes and runs `mkdocs gh-deploy`.
- **Updated `mkdocs.yml`:** Remove comments to test deployment.
- **Automate Documentation Deployment:** Eliminates the need for manual `mkdocs gh-deploy` commands, ensuring the documentation stays up-to-date.
- **Enhance Developer Experience:** Streamlines the process for contributors and maintainers, making it easier to manage and publish doc updates.
1. **Workflow Execution:** Verified that a push to the main branch with changes in `docs/**` or `mkdocs.yml` triggers the action.
2. **Successful Build:** …
> Set up GitHub Actions workflow for docs deployment

- .github/workflows/docs.yml
CI is failing due to missing plugin. Add mkdocs-static-i18n plugin in deploy.yml
> [CI] Add mkdocs-static-i18n plugin in deploy.yml

- docs/en/developer_guide/dev_setup.md
- mkdocs.yml
This update fixes broken image links in `docs/en/developer_guide/dev_setup.md` and changes the i18n configuration so that Japanese appears first (default) in `mkdocs.yml`.
- **Fixed Image Paths**: Adjusted broken links in `docs/en/developer_guide/dev_setup.md` to point to the correct `assets/images/` location.
- **Reordered i18n Languages**: Set Japanese (`ja`) as the default language in `mkdocs.yml`, and moved English (`en`) below it.
> Fix broken image links in English dev_setup document

- includes/class-wc-gateway-komoju-single-slug.php
This is a tiny tweak to make sure that we're not showing any field-related elements if Inline Fields are disabled.
> Do not give fields if it should not have any

- docs/en/index.md
- docs/en/user_guide/getting_started.md
- docs/ja/index.md
This pull request fix both the English and Japanese documentation:
- **Cleaned up `docs/en/index.md`** for clarity and consistency  
- **Corrected the Japanese link** in `docs/en/user_guide/getting_started.md` to point to `https://en.komoju.com/integrations/woocommerce/` instead of the Japanese URL  
- **Reduced and reorganized content** in `docs/ja/index.md` by removing detailed local payment lists (Since it is duplicated in features.md)
> Fix wrong link in English page and clean up Japanese Content

- Dockerfile
- README.md
- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- docker-compose.yml
- docs/en/developer_guide/dev_setup.md
- docs/ja/developer_guide/dev_setup.md
- index.php
- readme.txt
- tests/cypress/e2e/admin.cy.js
- tests/cypress/e2e/checkout.cy.js
This PR updates the plugin to **version 3.1.8**, aligning with the latest WordPress and WooCommerce versions, and streamlining our documentation.
- **WordPress & WooCommerce Compatibility**  
- Dockerfile: Bumped WordPress from `6.7.1` to `6.7.2`  
- Updated references to WooCommerce `9.7.1` (previously `9.5.2`)  
- Updated `readme.txt`’s “Tested up to” versions accordingly
- **Version Bump**  
- Updated plugin files (`index.php`, `class-wc-gateway-komoju.php`, etc.) to `3.1.8`
- **Documentation Revamp**  
- Rewrote `README.md` to be more concise, linking to external guides on [tech.degica.com](https://tech.degica.com/komoju-woocommerce/)  
- Added a quick-start guide link at the top of `readme.txt`  
- Removed redundant or outdated text, focusing on essential usage instructions
- **Dev …
> Bump version to 3.1.8

- docs/en/developer_guide/documenting.md
- docs/ja/developer_guide/documenting.md
- mkdocs.yml
This PR adds a documentation guide under `docs/en/developer_guide/documenting.md`. The guide explains how to edit existing documentation, add new pages, preview changes using Docker, and deploy updates via GitHub Actions.
- Created `docs/en/developer_guide/documenting.md` & `docs/ja/developer_guie/documenting.md`
- Provided instructions on using MkDocs Material for documentation
- Added guidelines for modifying and adding documentation pages
- Updated previewing steps using `docker compose up docs`
- Clarified the automatic deployment process via GitHub Actions
1. Run `docker compose up docs`
2. Open `http://127.0.0.1:7777/` in a browser
3. Verify that the documentation renders correctly
- Ensure that new documentation pages are properly added to `mkdocs.yml`
- Deployment occurs …
> Add Documenting page

- .github/workflows/docs.yml
- mkdocs.yml
This updates the documentation deployment workflow. Our docs deployment was failing with PAT. So, remove PAT and followed the official github guide to deploy docs.
- Replaces manual git commands with a cleaner, secure deployment step
- Deploys content from the ./site directory to the gh-pages branch
> Fix docs deployment failure

- class-wc-settings-page-komoju.php
- index.php
- tests/cypress/e2e/admin.cy.js
- tests/cypress/support/commands.js
This PR removes support for the LINE Pay payment method from the KOMOJU WooCommerce plugin, ensuring it is completely blocked from being registered, cached, or loaded as a payment gateway.
All the code added with `CPF-264` comment above, so we can find and remove these lines easily.
> [CPF-264] Block Line pay forcefully

- build.bash
GitHub has deprecated the usage of `set-output` syntax and advised user to pipe the output to `$GITHUB_OUTPUT` file instead: https://github.blog/changelog/2022-10-10-github-actions-deprecating-save-state-and-set-output-commands/
Note that the removal of this usage has been postponed for quite a few times, but we don't know when GitHub will pull this. So, it's best to just fix this.
> [CORE-600] Update usage of deprecated set-output syntax

- includes/class-wc-gateway-komoju-single-slug.php
This PR fixes a `missing_parameter` error thrown when creating a session in **WooCommerce** for merchants who have **Atone** enabled.  
The Komoju API requires the `line_items` parameter, which was previously missing in the session creation request.
---
- Added the `line_items` property to the `$session_params` array inside the `create_session_for_fields` method.
- `line_items` now includes:
- `amount`: same as the session `amount` in cents.
- `description`: hardcoded as `Purchase`.
- `quantity`: set to `1`.
> CPF-318 Add line_items property when creating session
