komoju/komoju-woocommerce

- index.php
While uploading the submissions I was informed that the Author URI and the Plugin URI cannot be the same value. So changing the Plugin URI to be this github repository.
> Change the Plugin URI

- readme.txt
We've updated the plugin name in the submission to be Komoju Japanese
Payments, so the readme.txt should be updated to reflect the change.
> Update Plugin name

- index.php
- readme.txt
Bumping the library to 1.0.1 to include the fix to the discount code made in #28.
> Bump version to 1.0.1

- docker-compose.yml
testing:
try `docker-compose up`, navigate to the app and confirm that no database connection error is shown
> fix docker compose build DB connection error

- .github/workflows/deploy.yml
adds missing step to deploy CI action
> fix deploy action

- class-wc-gateway-komoju.php
[WC_Order docs](https://woocommerce.github.io/code-reference/classes/WC-Order.html)
> Sends addresses to Sessions API

- README.md
Updating the docs as we are no longer offering POLi due to regulatory change.
> POLi no longer available

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- includes/api-settings-komoju.php
- includes/class-wc-gateway-komoju-ipn-handler.php
- includes/class-wc-gateway-komoju-response.php
- index.php
- readme.txt
Capture payments asynchronously using Action Scheduler
> Capture payments asynchronously

- .devcontainer/devcontainer.json
- Dockerfile
This'll let us use codespaces or VSCode's remote containers extension to dev this plugin.
> Devcontainer support

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- includes/class-wc-gateway-komoju-ipn-handler.php
- index.php
- readme.txt
Looks like we were still broken with currencies that use cents.
I'll write an e2e test for this separately.
> Use to_cents instead of number_format

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- includes/class-wc-gateway-komoju-ipn-handler.php
- index.php
- readme.txt
We had some leftover currency check code in our capture handler.
Fixes #12
> Remove currency check on capture

- includes/class-wc-gateway-komoju-ipn-handler.php
refs https://github.com/degica/komoju-woocommerce/pull/84 https://github.com/degica/komoju-woocommerce/issues/83
> Fix cancelling a captured payment

- README.md
- docs/dev_setup.md
- readme.txt
Replaced versions written in the docs.
- Wordpress: 6.1.1 https://github.com/degica/komoju-woocommerce/blob/7f3cf78ab3425fc8c51b256e769f7defafe14321/Dockerfile#L1
- WooCommerce: 6.3.1 https://github.com/degica/komoju-woocommerce/blob/7f3cf78ab3425fc8c51b256e769f7defafe14321/docker-compose.yml#L24
> Update versions in docs

- README.md
- index.php
- readme.txt
Pre-release update.
- changelog updates
- version update
**!!!!! Please dont merge this PR, just LGTM it !!!!!** 
( to actually release a new version i have to add a git tag, i want to do it at the same time as this PR is merged )
> Pre-release preparations

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- index.php
- readme.txt
Just updating the version number so we can release the latest version of our code.
> Update plugin to Version 3.0.9

- readme.txt
Update readme.txt for 3.1.0 update
> Update readme.txt for 3.1.0

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- index.php
- readme.txt
Since we moved the use on-hold menu, I've updated the release version and readme.txt before the release.
> Update version to 3.1.7

- .github/workflows/docs.yml
- mkdocs.yml
In #134 , I set the wrong target branch for deploying docs. Changing it to master.
> Change target branch to master in docs.yml

- README.md
- docs/en/user_guide/getting_started.md
- readme.txt
Smart tag in readme file was causing a trouble. Replacing with standard quotes.
> Replace smart quotes (’) with standard quotes (')

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- index.php
- readme.txt
> Bump version to 3.1.9

- class-wc-gateway-komoju.php
- class-wc-settings-page-komoju.php
- index.php
- readme.txt
> Update version to 3.2.0
